language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - gh-pages
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_3352ebe59dce_key -iv $encrypted_3352ebe59dce_iv
  -in travis_ci_rsa.enc -out ./travis_ci_rsa -d
- set -e
install:
- yarn install
- yarn global add codecov
script:
- yarn run test 
- yarn run build
- yarn run build-storybook
after_success:
- codecov
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  bash ./gh-pages-deploy.sh; fi
