language: node_js
node_js:
- '8'
before_install:
  - >-
    openssl aes-256-cbc -K $encrypted_3352ebe59dce_key -iv $encrypted_3352ebe59dce_iv -in travis_ci_rsa.enc -out ./travis_ci_rsa -d
install: 
  - yarn install  
script: 
  - yarn run build-storybook   